version: '3'
services:
  mutants:
    build: .
    depends_on:
      - mongodb
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo:3.6.0
    ports:
    - "27017:27017"
    volumes:
    - dbvolume:/data
    environment: {
      AUTH: "no"
    }
volumes:
  dbvolume: {}